"""add_slug_to_problems

Revision ID: 63bd2f3e53ba
Revises: b84faeef9437
Create Date: 2025-06-09 23:40:50.963437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63bd2f3e53ba'
down_revision: Union[str, None] = 'b84faeef9437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_column('problems', 'slug')
    # ### end Alembic commands ###
